output: /srv/http/poll_ast/admin/runtime/reportPoll_730.sav
varNames:
    - id
    - created
    - q1
varTypes:
    id: 0
    created: 255
    q1: 255
varLabels:
    id: Ид
    created: Создано
    q1: Как дела?
formats:
    id: F40
    created: A255
    q1: A255
valueLabels:
    q1:
        b'0': Да
        b'1': Нет
records:
    - [11, '12.11.2004 23:55', 0]
    - [12, '02.03.2004 14:23', 1]